In [14]:
# Python program for
# Creation of Arrays
import numpy as np

arr = np.array([2,3,4,'reur0wer','1.2'])

print("Array with Rank 1: \n",arr)
arr = np.array([[2,3,4],[839,'fdssd']])
print("Array with Rank 2: \n",arr)

arr = np.array((1,2))
print("Array with Rank 2: \n",arr)

Array with Rank 1: 
 ['2' '3' '4' 'reur0wer' '1.2']
Array with Rank 2: 
 [list([2, 3, 4]) list([839, 'fdssd'])]
Array with Rank 2: 
 [1 2]


<ipython-input-14-ebb894c1706a>:8: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = np.array([[2,3,4],[839,'fdssd']])


In [30]:
#slicing a array
import numpy as np

arr = np.array([[6,49,7],[373,95,9]])

print("Array with Rank 1: \n",arr)

print("Fetch first element: \n",arr[0])

print("Fetch second element: \n",arr[1])

print("Fetch seconnd item of first element: \n",arr[0][1])

print("Fetch seconnd item of second element: \n",arr[1][1])


arr = np.array((6,49,7))


print("Array with Rank 1: \n",arr)

print("fetch first element: \n",arr[0])

print("fetch second element: \n",arr[1])

print("fetch third element: \n",arr[2])


arr = np.array([6,49,'ddsdss'])

print("Array with Rank 1: \n",arr)

print("fetch first element: \n",arr[0])

print("fetch second element: \n",arr[1])

print("fetch third element: \n",arr[2])


arr = np.array((6,7))

print("Array with Rank 1: \n",arr)



Array with Rank 1: 
 [[  6  49   7]
 [373  95   9]]
Fetch first element: 
 [ 6 49  7]
Fetch second element: 
 [373  95   9]
Fetch seconnd item of first element: 
 49
Fetch seconnd item of second element: 
 95
Array with Rank 1: 
 [ 6 49  7]
fetch first element: 
 6
fetch second element: 
 49
fetch third element: 
 7
Array with Rank 1: 
 ['6' '49' 'ddsdss']
fetch first element: 
 6
fetch second element: 
 49
fetch third element: 
 ddsdss
Array with Rank 1: 
 [6 7]


In [18]:
# Python program to demonstrate
# indexing in numpy array
import numpy as np
 
# Initial Array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

print("Initial Array: ")
print(arr)
print ('------------------------------')
sliced_arr = arr[:4]
print(sliced_arr)


Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
------------------------------
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]


In [28]:
# Python program to demonstrate
# basic operations on single array
import numpy as np

# Defining Array 1
a = np.array([[1, 2],
              [3, 4]])
 
# Defining Array 2
b = np.array([[4, 3],
              [2, 1]])

print(' adding 1 to each elements of arr a ', a+1)

print(' multiply by 2 in array b ', b*2)


# sum of array elements
# Performing Unary operations
print ("\nSum of all array "
       "elements: ", a.sum())

print ("\nArray sum:\n", a[0] + b[0])
 

 adding 1 to each elements of arr a  [[2 3]
 [4 5]]
 multiply by 2 in array b  [[8 6]
 [4 2]]

Sum of all array elements:  10

Array sum:
 [5 5]


In [29]:
#check if list is empty
def Enquiry(lis1):
    if len(lis1)==0:
        return 0
    else:
        return 1


lis1 = []
if Enquiry(lis1):
    print ("The list is not empty")
else:
    print("Empty List")


Empty List


In [30]:
#check if list is empty
def Enquiry(lis1):
    if not lis1:
        return 0
    else:
        return 1


lis1 = []
if Enquiry(lis1):
    print ("The list is not empty")
else:
    print("Empty List")


Empty List


In [3]:
#check if list is empty
def Enquiry(tuple):
    if not tuple:
        return 0
    else:
        return 1


tuple = ()
if Enquiry(tuple):
    print ("The list is not tuple")
else:
    print("Empty tuple")

Empty tuple


In [5]:
#check if list is empty
def Enquiry(dic):
    if not dic:
        return True
    else:
        return False


dic = {}
if Enquiry(dic):
    print ("The dic is not dic")
else:
    print("Empty dic")

The list is not dic


In [15]:
import numpy

# Driver Code
lis1 = (1)

print(numpy.array(lis1).size)


1


In [30]:
import numpy

# Driver Code
lis1 = [1,3,53,43,3,3]

print(numpy.unique(lis1))

Myset = set(lis1)
print(tup)


[ 1  3 43 53]
{1, 3, 53, 43}


In [31]:
from functools import reduce
list1 = [1, 2, 3]
list2 = [3, 2, 4]
 
 
result1 = reduce((lambda x, y: x * y), list1)
result2 = reduce((lambda x, y: x * y), list2)
print(result1)
print(result2)

6
24


In [32]:
A='1234567'
print(A[1::2])

246


In [33]:
Name="Michael Jackson"
print(Name.find('el'))

5


In [34]:
A='1'
B='2'
print(A+B)

12


In [35]:
F="You are wrong"
print(F.upper())

YOU ARE WRONG


In [36]:
V={'A','B'}
V.add('C')
print(V)

{'B', 'C', 'A'}


In [37]:
V={'A','B','C' }
V.add('C')
print(V)

{'B', 'C', 'A'}


In [39]:
for n in range(3):
    print(n)

0
1
2


In [41]:
A=['1','2','3']

for a in A:
    print(2*a)


11
22
33


In [45]:
class Points(object):

    def __init__(self,x,y):
        self.x=x
        self.y=y

    def print_point(self):

        print('x=',self.x,'y=',self.y)

In [14]:
from statistics import mode
mode([2,3,5,7])


2